name: Build Meshfinity for macOS (ARM)

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-mac:
    name: Build Meshfinity for macOS (ARM)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: notiz-dev/github-action-json-property@release
        id: version
        with:
          path: "version.json"
          prop_path: "version"
      - run: NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      - run: /opt/homebrew/bin/brew install python@3.12 || true # This returns exit code 1 even if successful - why ??
      - run: ./build-mac-arm.sh
        timeout-minutes: 60
      - run: ditto -c -k --sequesterRsrc --keepParent dist/Meshfinity.app meshfinity-${{ steps.version.outputs.prop }}-mac-arm.zip
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.prop }}
          files: meshfinity-${{ steps.version.outputs.prop }}-mac-arm.zip
